name: Run UnitTest

on:
  push:
    branches: [ "*" ]
    paths: [ "external/**", "Typoon/**", "UnitTest/**", "Typoon.sln" ]

  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

env:
  SOLUTION_FILE_PATH: .

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Release, Debug]

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: chcp 65001; msbuild /m /t:UnitTest /p:Configuration=${{matrix.configuration}} /p:Platform=x64 ${{env.SOLUTION_FILE_PATH}}

    - name: Test
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: chcp 65001; ./x64/${{matrix.configuration}}/UnitTest.exe
