name: Run UnitTest

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  PROJ_FILE_PATH: ./UnitTest

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Release, Debug]

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{matrix.configuration}};Platform=x64 ${{env.PROJ_FILE_PATH}}

    - name: Test
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./${{matrix.configuration}}/UnitTest.exe
